---
- name: "Self Installation of Laptop"
  become: yes
  hosts: localhost
  connection: local
  roles:
  - Packages
  - SoftwareUnpackaged
  post_tasks:
  - name: Installation des fonds d'écrans
    copy:
      src: Wallpapers
      dest: /home/theophile/Images

  - name: Add ansible-pull cron job
    cron:
      name: Ansible auto-provision
      user: root
      hour: "*/1"
      job: ansible-pull -o -U https://github.com/Eliora59/SelfInstall.git

  - name: Templétisation de .vimrc
    template:
      src: vimrc.j2
      dest: /home/theophile/.vimrc

  - name: Ajout du raccourci d'Ankama Launcher
    file:
      src: ankamalauncher.desktop
      dest: /usr/share/applications/

  - name: Ajout du logo d'Ankama Launcher
    file:
      src: ankamalauncher.png
      dest: /usr/share/icons/

        ##################################### Can't reboot Localhost, "Running reboot with local connection would reboot the control node"
        # - name: "Reboot of Laptop"
        #   reboot:
        #     msg: "Reboot from Ansible"
        #     reboot_timeout: 120
        #     test_command: uptime
        #   delegate_to: localhost
        #test