---
- name: Full upgrade and installation packages of Debian
  apt:
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
    install_recommends: yes
    name:
      - apt-transport-https
      - aptitude
      - bison
      - build-essential
      - ca-certificates
      - cinnamon
      - curl
      - dirmngr
      - dkms
      - docker
      - docker.io
      - docker-compose
      - dynamips
      - firefox-esr-l10n-fr
      - firmware-iwlwifi
      - firmware-misc-non-free
      - firmware-realtek
      - git
      - gnome-terminal
      - gnupg
      - htop
      - hydra
      - intel-microcode
      - keepassxc
      - laptop-detect
      - linux-source
      - macchanger
      - net-tools
      - nmap
      - postgresql          # Require for Metasploit-Framework
      - python3-pip
      - python3-sip
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qtwebsockets
      - software-properties-common
      - thunderbird
      - thunderbird-l10n-fr
      - tor
      - tree
      - vim
      - wireshark
      - wireshark-qt
      - yersinia
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Full upgrade ArchLinux
  pacman: 
    update_cache: yes
    state: latest
    name:
      - base-devel
      - bison
      - ca-certificates
      - cinnamon
      - curl
      - dkms
      - firefox
      - git
      - gnome-terminal
      - gnupg
      - htop
      - hydra
      - keepassxc
      - laptop-detect
      - macchanger
      - net-tools
      - nmap
      - postgresql
      - python
      - python-sip
      - python-pyqt5
      - thunderbird
      - tor
      - tree
      - vim
      - wireshark-qt
  when: ansible_distribution == "Archlinux"

  # firmware-iwlwifi
  # firmware-realtek
  # dirmngr
  # dynamips
  # intel-microcode
  # yersinia

- name: Full upgrade of Rhel or CentOS
  yum: 
    update_cache: yes
    update_only: yes
    state: latest
    name:
      - bison
      - dkms
      - firefox
      - git
      - gnome-terminal
      - htop
      - keepassxc
      - nmap
      - postgresql
      - python3-pip
      - thunderbird
      - tor
      - tree
      - vim
      - wireshark
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

  # hydra
  # laptop-detect
  # macchanger