---
- name: Installation of Visual Studio Code
  shell:
    cmd: "{{ item }}"
  with_items:
  - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg 
  - install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ 
  - sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/Visual_Studio_Code.list' 
  - rm -f packages.microsoft.gpg
- name: Installation of the key for VirtualBox
  apt_key:
    url: "{{ item }}"
  with_items:
  - https://www.virtualbox.org/download/oracle_vbox.asc
  - https://www.virtualbox.org/download/oracle_vbox_2016.asc
- name: Installation of repository for VirtualBox
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian eoan contrib"
    filename: "Virtualbox"
- name: Installation of Metasploit FrameWork
  shell:
    cmd: "{{ item }}"
  with_items:
  - curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
  - chmod 755 msfinstall
  - bash msfinstall
- name: Installation of Spotify's key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
- name: Installation of Spotify's repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    filename: Spotify      
- name: Installation GNS3 via pip
  pip:
    name: 
      - gns3-server
      - gns3-gui
- name: Installation de la clef GNS3 pour le ppa pour VPC version 0.6.1
  shell:
    cmd: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F88F6D313016330404F710FC9A2FD067A2E3EF7B
- name: Installation du repo GNS3 pour le ppa pour VPC version 0.6.1
  apt_repository:
    codename: xenial
    filename: GNS3
    repo: deb http://ppa.launchpad.net/gns3/ppa/ubuntu xenial main
    update_cache: yes
- name: Install VPCS in 0.6.1
  apt:
    update_cache: yes
    name: 
    - vpcs
    - dynamips
    - ubridge
- name: Mark hold VPCS in 0.6.1
  dpkg_selections:
    name: vpcs
    selection: hold
- name: Installation of Terraform
  shell:
    cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    cmd: apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    cmd : apt-get update && sudo apt-get install terraform